Update client.dart
hide `HttpLinkHeaders` and `HttpLinkResponseContext` to resolve dependency clashing resulting to the error below.
```text
Error: 'HttpLinkHeaders' is exported from both 'package:gql_exec/src/http.dart' and 'package:gql_http_link/src/link.dart'.
../…/lib/client.dart:10
export 'package:graphql/src/links/links.dart';

Error: 'HttpLinkResponseContext' is exported from both 'package:gql_exec/src/http.dart' and 'package:gql_http_link/src/link.dart'.
../…/lib/client.dart:10
export 'package:graphql/src/links/links.dart';
```